### ISSUE TITLE
bug: alignment issues

### ISSUE THREAD

**Issue by nimish-nimishmittal** [Nityom/Edu-site#1]
This is the alignment issue in its home page itself; kindly check.
![image](https://github.com/Nityom/Edu-site/assets/69715712/9f14fe01-f1b2-412b-8da1-392abdd15b78)

i think the background image should be made width: 100% in the css.

**Comment by Nityom** [comment]
I don't know why the images are not loading in the live preview link but , it's working fine on online image links

**Comment by nimish-nimishmittal** [comment]
okay i gotta check it once more and i'll put a pr to your repo once i am done with the edits.
